import { sql } from "drizzle-orm";
import { pgTable, text, varchar, timestamp, integer, jsonb, serial } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  selectedIndustry: text("selected_industry"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
});

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;

// Companies detected from news
export const companies = pgTable("companies", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  domain: text("domain"),
  industry: text("industry"),
  logoPlaceholder: text("logo_placeholder"),
  homepageSummary: text("homepage_summary"), // Semantic summary from LLM analysis
  lastSeen: timestamp("last_seen").defaultNow(),
});

export const insertCompanySchema = createInsertSchema(companies).omit({
  id: true,
  lastSeen: true,
});

export type InsertCompany = z.infer<typeof insertCompanySchema>;
export type Company = typeof companies.$inferSelect;

// Intelligence Events (the core signal)
export const events = pgTable("events", {
  id: serial("id").primaryKey(),
  companyId: integer("company_id").references(() => companies.id).notNull(),
  eventType: text("event_type").notNull(), // rebrand, new_exec_hire, etc.
  date: timestamp("date").notNull(),
  summary: text("summary").notNull(),
  sourceUrl: text("source_url"),
  issues: text("issues").array(), // ["Positioning", "Differentiation"]
  impactScore: integer("impact_score").default(50),
  rawArticle: jsonb("raw_article"), // Store original article JSON
  processedAt: timestamp("processed_at").defaultNow(),
});

export const insertEventSchema = createInsertSchema(events).omit({
  id: true,
  processedAt: true,
});

export type InsertEvent = z.infer<typeof insertEventSchema>;
export type Event = typeof events.$inferSelect;

// Leadership / Contact Information
export const leadership = pgTable("leadership", {
  id: serial("id").primaryKey(),
  companyId: integer("company_id").references(() => companies.id).notNull(),
  name: text("name").notNull(),
  title: text("title").notNull(),
  verified: integer("verified").default(0), // 0 = false, 1 = true (sqlite compat)
  profileUrl: text("profile_url"),
});

export const insertLeadershipSchema = createInsertSchema(leadership).omit({
  id: true,
});

export type InsertLeadership = z.infer<typeof insertLeadershipSchema>;
export type Leadership = typeof leadership.$inferSelect;

// Conversation Starters (generated by LLM)
export const conversationStarters = pgTable("conversation_starters", {
  id: serial("id").primaryKey(),
  eventId: integer("event_id").references(() => events.id).notNull(),
  role: text("role").notNull(), // CMO, CRO, etc.
  starter: text("starter").notNull(),
  generatedAt: timestamp("generated_at").defaultNow(),
});

export const insertConversationStarterSchema = createInsertSchema(conversationStarters).omit({
  id: true,
  generatedAt: true,
});

export type InsertConversationStarter = z.infer<typeof insertConversationStarterSchema>;
export type ConversationStarter = typeof conversationStarters.$inferSelect;
